name: CI/CD

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_1: "aliezan/personal-portfolio"
  IMAGE_NAME_2: "aliezan/personal-portfolio-strapi"

jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push nextjs image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_1 }}:latest
          build-args: |
            NEXT_PUBLIC_STRAPI_URL=${{secrets.NEXT_PUBLIC_STRAPI_URL}}
            NEXT_PUBLIC_BASE_URL=${{secrets.NEXT_PUBLIC_BASE_URL}}

      # - name: Build and push strapi image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./strapi-blog
      #     file: strapi-blog/Dockerfile.prod
      #     platforms: linux/amd64
      #     push: true
      #     tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_2 }}:latest

      # - name: Deploy to Coolify (nextjs-fe)
      #   run: |
      #     curl --request GET '${{ secrets.COOLIFY_WEBHOOK_NEXTJS }}' \
      #          --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'

      # - name: Deploy to Coolify (strapi-cms)
      #   run: |
      #     curl --request GET '${{ secrets.COOLIFY_WEBHOOK_STRAPI }}' \
      #          --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
